version: '3'

services:
  web:
    build: .
    container_name: web
    ports:
      - 8062:6000

  mongodb:
    image: mongo:4.0.4
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    command: mongod


volumes:
  mongodb:
  mongodb_config:
