version: '3'

services:
  web1:
    build: .
    container_name: web1
    ports:
      - 8062:6000
    links:
      - db

  web2:
    build: .
    container_name: web2
    ports:
      - 8063:6000
    links:
      - db

  web3:
    build: .
    container_name: web3
    ports:
      - 8064:6000
    links:
      - db

  db:
    image: mongo:4.0.1
    ports:
      - 27017:27017
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    command: mongod

  html:
    build:
      context: .
      dockerfile: Dockerfile-Front
    container_name: html
    ports:
      - 80:80
    links:
      - web1
      - web2
      - web3

volumes:
  mongodb:
  mongodb_config:
